# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123b1fa4d9a887e6a1256ddc53634b9628241eb73e7222c5a0c54f308277edbc1f24d2625d479734c575903e96656883ccc223d9c7cf3fce0ce59342baebf33d

test:
  secret_key_base: c5bc38b7b1755cfce6735b6220d899a871f9b9c43e5f3a8f1e531120e1cc6581998c5fbe8fb2ea78cdce0857f80ae92dd81b7e2d0faf9c2ad8273fc7eb6b5c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
